import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, Shield } from 'lucide-react';

const Terms = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background text-gray-300 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto bg-surface border border-border rounded-2xl p-6 sm:p-10 shadow-xl">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-10 pb-6 border-b border-border">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-primary/10 rounded-lg">
              <Shield className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h1 className="text-2xl sm:text-3xl font-bold text-white">Terms & Conditions</h1>
              <p className="text-sm text-gray-500 mt-1">Last updated: June 7, 2026</p>
            </div>
          </div>
          <button 
            onClick={() => navigate('/')}
            className="flex items-center justify-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 rounded-lg text-sm font-medium transition border border-border"
          >
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </button>
        </div>

        {/* Content Section */}
        <div className="space-y-8 text-sm sm:text-base leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Onowl AI, you agree to be bound by these Terms and Conditions. If you do not agree to all of these terms, do not use our services. We reserve the right to modify these terms at any time, and your continued use of the platform constitutes acceptance of updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">2. Description of Service</h2>
            <p>
              Onowl AI provides an integrated development environment (IDE) powered by artificial intelligence. Our services include code generation, file management, and workspace synchronization across devices. Some features are subject to subscription limits as defined in our Pricing policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">3. User Accounts</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We use Supabase for secure authentication; however, you remain liable for activities occurring under your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">4. Subscription and Payments</h2>
            <p>
              Usage limits are determined by your selected plan (Free, Pro, Premium, or Business). Tokens are used for AI completions and are reset every 24 hours based on UTC time. Access to advanced features like ZIP exports and single-file downloads requires a paid subscription.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">5. Intellectual Property</h2>
            <p>
              The code generated by Onowl AI is your property. However, the Onowl AI platform, its design, logo, and underlying technology are protected by intellectual property laws and belong to Onowl AI Inc. You may not reverse engineer or attempt to extract our proprietary code.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">6. Limitation of Liability</h2>
            <p>
              Onowl AI is provided "as is" without warranties of any kind. We are not responsible for any data loss, code errors, or downtime caused by AI generations or server maintenance. Users should always backup their workspaces using our export features.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-4">7. Termination</h2>
            <p>
              We reserve the right to terminate or suspend your access to our services at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users or our business interests.
            </p>
          </section>
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-border text-center">
          <p className="text-sm text-gray-500">
            Have questions about our terms? <button onClick={() => navigate('/contact')} className="text-primary hover:underline font-medium">Contact Support</button>
          </p>
          <p className="text-xs text-gray-600 mt-4">
            © 2026 Onowl AI Inc. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
};

export default Terms;
